In [12]:
# Import the pandas library and give it an alias 'pd' for easy reference

import pandas as pd

The pandas library provides powerful data structures for data analysis and manipulation.

is a common alias used for pandas, which allows you to access its functions in a more concise manner.

Example: Creating a DataFrame (table of data) with pandas

In [13]:
mydataset = { 'cars':['toyota', 'BMW', 'crolla'], 
             'Model':[1997, 2024, 2002] }

In [14]:
print(mydataset)

{'cars': ['toyota', 'BMW', 'crolla'], 'Model': [1997, 2024, 2002]}

In [16]:
myvar = pd.DataFrame(mydataset)

In [17]:
myvar

     cars  Model
0  toyota   1997
1     BMW   2024
2  crolla   2002

In [18]:
myvar['Model']

0    1997
1    2024
2    2002
Name: Model, dtype: int64

In [19]:
# The `__version__` attribute of a library like pandas stores the version number.
# This is useful for checking which version of pandas is installed in your environment.

print(pd.__version__)

1.4.2

In [20]:
a = [1,2,3,4,5,6,7,8]

In [21]:
a

[1, 2, 3, 4, 5, 6, 7, 8]

In [23]:
var1 = pd.Series(a)

In [24]:
var1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [26]:
# Explanation:
# pd.read_csv() is a function from the pandas library that is used to read a CSV (Comma-Separated Values) file.
# It takes the file path (or URL) as an argument and returns a DataFrame, which is a table-like structure.
# The argument 'dataset.csv' is the name of the file you're loading. Make sure the file is in the current working directory or specify the full file path.

df = pd.read_csv('dataset.csv')

In [27]:
# Display the first 5 rows of the DataFrame
df.head()

     Cars  Model
0  toyota   1997
1     bmw   2024

In [29]:
df = pd.read_csv('data.csv')

In [30]:
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [31]:
# Display the last 5 rows of the DataFrame
df.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [32]:
# Display all rows of the DataFrame
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [33]:
# Display summary information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

Explanation:
 The `info()` method provides a concise summary of the DataFrame.
It shows:
  1. The number of rows and columns in the DataFrame.
  2. The name of each column.
  3. The data type of each column (e.g., int64, float64, object, etc.).
  4. The number of non-null (non-missing) entries in each column.
  5. The memory usage of the DataFrame (can be useful for large datasets).

In [36]:
# Check for missing values in the DataFrame
print(df.isnull().to_string())

     Duration  Pulse  Maxpulse  Calories
0       False  False     False     False
1       False  False     False     False
2       False  False     False     False
3       False  False     False     False
4       False  False     False     False
5       False  False     False     False
6       False  False     False     False
7       False  False     False     False
8       False  False     False     False
9       False  False     False     False
10      False  False     False     False
11      False  False     False     False
12      False  False     False     False
13      False  False     False     False
14      False  False     False     False
15      False  False     False     False
16      False  False     False     False
17      False  False     False      True
18      False  False     False     False
19      False  False     False     False
20      False  False     False     False
21      False  False     False     False
22      False  False     False     False
23      False  False     False     False
24      False  False     False     False
25      False  False     False     False
26      False  False     False     False
27      False  False     False      True
28      False  False     False     False
29      False  False     False     False
30      False  False     False     False
31      False  False     False     False
32      False  False     False     False
33      False  False     False     False
34      False  False     False     False
35      False  False     False     False
36      False  False     False     False
37      False  False     False     False
38      False  False     False     False
39      False  False     False     False
40      False  False     False     False
41      False  False     False     False
42      False  False     False     False
43      False  False     False     False
44      False  False     False     False
45      False  False     False     False
46      False  False     False     False
47      False  False     False     False
48      False  False     False     False
49      False  False     False     False
50      False  False     False     False
51      False  False     False     False
52      False  False     False     False
53      False  False     False     False
54      False  False     False     False
55      False  False     False     False
56      False  False     False     False
57      False  False     False     False
58      False  False     False     False
59      False  False     False     False
60      False  False     False     False
61      False  False     False     False
62      False  False     False     False
63      False  False     False     False
64      False  False     False     False
65      False  False     False     False
66      False  False     False     False
67      False  False     False     False
68      False  False     False     False
69      False  False     False     False
70      False  False     False     False
71      False  False     False     False
72      False  False     False     False
73      False  False     False     False
74      False  False     False     False
75      False  False     False     False
76      False  False     False     False
77      False  False     False     False
78      False  False     False     False
79      False  False     False     False
80      False  False     False     False
81      False  False     False     False
82      False  False     False     False
83      False  False     False     False
84      False  False     False     False
85      False  False     False     False
86      False  False     False     False
87      False  False     False     False
88      False  False     False     False
89      False  False     False     False
90      False  False     False     False
91      False  False     False      True
92      False  False     False     False
93      False  False     False     False
94      False  False     False     False
95      False  False     False     False
96      False  False     False     False
97      False  False     False     False
98      False  False     False     False
99      False  False     False     False
100     False  False     False     False
101     False  False     False     False
102     False  False     False     False
103     False  False     False     False
104     False  False     False     False
105     False  False     False     False
106     False  False     False     False
107     False  False     False     False
108     False  False     False     False
109     False  False     False     False
110     False  False     False     False
111     False  False     False     False
112     False  False     False     False
113     False  False     False     False
114     False  False     False     False
115     False  False     False     False
116     False  False     False     False
117     False  False     False     False
118     False  False     False      True
119     False  False     False     False
120     False  False     False     False
121     False  False     False     False
122     False  False     False     False
123     False  False     False     False
124     False  False     False     False
125     False  False     False     False
126     False  False     False     False
127     False  False     False     False
128     False  False     False     False
129     False  False     False     False
130     False  False     False     False
131     False  False     False     False
132     False  False     False     False
133     False  False     False     False
134     False  False     False     False
135     False  False     False     False
136     False  False     False     False
137     False  False     False     False
138     False  False     False     False
139     False  False     False     False
140     False  False     False     False
141     False  False     False      True
142     False  False     False     False
143     False  False     False     False
144     False  False     False     False
145     False  False     False     False
146     False  False     False     False
147     False  False     False     False
148     False  False     False     False
149     False  False     False     False
150     False  False     False     False
151     False  False     False     False
152     False  False     False     False
153     False  False     False     False
154     False  False     False     False
155     False  False     False     False
156     False  False     False     False
157     False  False     False     False
158     False  False     False     False
159     False  False     False     False
160     False  False     False     False
161     False  False     False     False
162     False  False     False     False
163     False  False     False     False
164     False  False     False     False
165     False  False     False     False
166     False  False     False     False
167     False  False     False     False
168     False  False     False     False

In [37]:
#Check for non-null (valid) values in the DataFrame
print(df.notnull().to_string())

     Duration  Pulse  Maxpulse  Calories
0        True   True      True      True
1        True   True      True      True
2        True   True      True      True
3        True   True      True      True
4        True   True      True      True
5        True   True      True      True
6        True   True      True      True
7        True   True      True      True
8        True   True      True      True
9        True   True      True      True
10       True   True      True      True
11       True   True      True      True
12       True   True      True      True
13       True   True      True      True
14       True   True      True      True
15       True   True      True      True
16       True   True      True      True
17       True   True      True     False
18       True   True      True      True
19       True   True      True      True
20       True   True      True      True
21       True   True      True      True
22       True   True      True      True
23       True   True      True      True
24       True   True      True      True
25       True   True      True      True
26       True   True      True      True
27       True   True      True     False
28       True   True      True      True
29       True   True      True      True
30       True   True      True      True
31       True   True      True      True
32       True   True      True      True
33       True   True      True      True
34       True   True      True      True
35       True   True      True      True
36       True   True      True      True
37       True   True      True      True
38       True   True      True      True
39       True   True      True      True
40       True   True      True      True
41       True   True      True      True
42       True   True      True      True
43       True   True      True      True
44       True   True      True      True
45       True   True      True      True
46       True   True      True      True
47       True   True      True      True
48       True   True      True      True
49       True   True      True      True
50       True   True      True      True
51       True   True      True      True
52       True   True      True      True
53       True   True      True      True
54       True   True      True      True
55       True   True      True      True
56       True   True      True      True
57       True   True      True      True
58       True   True      True      True
59       True   True      True      True
60       True   True      True      True
61       True   True      True      True
62       True   True      True      True
63       True   True      True      True
64       True   True      True      True
65       True   True      True      True
66       True   True      True      True
67       True   True      True      True
68       True   True      True      True
69       True   True      True      True
70       True   True      True      True
71       True   True      True      True
72       True   True      True      True
73       True   True      True      True
74       True   True      True      True
75       True   True      True      True
76       True   True      True      True
77       True   True      True      True
78       True   True      True      True
79       True   True      True      True
80       True   True      True      True
81       True   True      True      True
82       True   True      True      True
83       True   True      True      True
84       True   True      True      True
85       True   True      True      True
86       True   True      True      True
87       True   True      True      True
88       True   True      True      True
89       True   True      True      True
90       True   True      True      True
91       True   True      True     False
92       True   True      True      True
93       True   True      True      True
94       True   True      True      True
95       True   True      True      True
96       True   True      True      True
97       True   True      True      True
98       True   True      True      True
99       True   True      True      True
100      True   True      True      True
101      True   True      True      True
102      True   True      True      True
103      True   True      True      True
104      True   True      True      True
105      True   True      True      True
106      True   True      True      True
107      True   True      True      True
108      True   True      True      True
109      True   True      True      True
110      True   True      True      True
111      True   True      True      True
112      True   True      True      True
113      True   True      True      True
114      True   True      True      True
115      True   True      True      True
116      True   True      True      True
117      True   True      True      True
118      True   True      True     False
119      True   True      True      True
120      True   True      True      True
121      True   True      True      True
122      True   True      True      True
123      True   True      True      True
124      True   True      True      True
125      True   True      True      True
126      True   True      True      True
127      True   True      True      True
128      True   True      True      True
129      True   True      True      True
130      True   True      True      True
131      True   True      True      True
132      True   True      True      True
133      True   True      True      True
134      True   True      True      True
135      True   True      True      True
136      True   True      True      True
137      True   True      True      True
138      True   True      True      True
139      True   True      True      True
140      True   True      True      True
141      True   True      True     False
142      True   True      True      True
143      True   True      True      True
144      True   True      True      True
145      True   True      True      True
146      True   True      True      True
147      True   True      True      True
148      True   True      True      True
149      True   True      True      True
150      True   True      True      True
151      True   True      True      True
152      True   True      True      True
153      True   True      True      True
154      True   True      True      True
155      True   True      True      True
156      True   True      True      True
157      True   True      True      True
158      True   True      True      True
159      True   True      True      True
160      True   True      True      True
161      True   True      True      True
162      True   True      True      True
163      True   True      True      True
164      True   True      True      True
165      True   True      True      True
166      True   True      True      True
167      True   True      True      True
168      True   True      True      True

In [40]:
# Remove rows with missing values from the DataFrame and print the result as a string
print(df.dropna().to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [41]:
# Calculate the mean (average) value of the 'Calories' column
mean1 = df['Calories'].mean()

In [42]:
mean1

375.79024390243916

In [43]:
# Fill missing values in the 'Calories' column with the mean value
df['Calories'].fillna(mean1, inplace = True)

In [44]:
print(df.to_string())

     Duration  Pulse  Maxpulse     Calories
0          60    110       130   409.100000
1          60    117       145   479.000000
2          60    103       135   340.000000
3          45    109       175   282.400000
4          45    117       148   406.000000
5          60    102       127   300.000000
6          60    110       136   374.000000
7          45    104       134   253.300000
8          30    109       133   195.100000
9          60     98       124   269.000000
10         60    103       147   329.300000
11         60    100       120   250.700000
12         60    106       128   345.300000
13         60    104       132   379.300000
14         60     98       123   275.000000
15         60     98       120   215.200000
16         60    100       120   300.000000
17         45     90       112   375.790244
18         60    103       123   323.000000
19         45     97       125   243.000000
20         60    108       131   364.200000
21         45    100       119   282.000000
22         60    130       101   300.000000
23         45    105       132   246.000000
24         60    102       126   334.500000
25         60    100       120   250.000000
26         60     92       118   241.000000
27         60    103       132   375.790244
28         60    100       132   280.000000
29         60    102       129   380.300000
30         60     92       115   243.000000
31         45     90       112   180.100000
32         60    101       124   299.000000
33         60     93       113   223.000000
34         60    107       136   361.000000
35         60    114       140   415.000000
36         60    102       127   300.000000
37         60    100       120   300.000000
38         60    100       120   300.000000
39         45    104       129   266.000000
40         45     90       112   180.100000
41         60     98       126   286.000000
42         60    100       122   329.400000
43         60    111       138   400.000000
44         60    111       131   397.000000
45         60     99       119   273.000000
46         60    109       153   387.600000
47         45    111       136   300.000000
48         45    108       129   298.000000
49         60    111       139   397.600000
50         60    107       136   380.200000
51         80    123       146   643.100000
52         60    106       130   263.000000
53         60    118       151   486.000000
54         30    136       175   238.000000
55         60    121       146   450.700000
56         60    118       121   413.000000
57         45    115       144   305.000000
58         20    153       172   226.400000
59         45    123       152   321.000000
60        210    108       160  1376.000000
61        160    110       137  1034.400000
62        160    109       135   853.000000
63         45    118       141   341.000000
64         20    110       130   131.400000
65        180     90       130   800.400000
66        150    105       135   873.400000
67        150    107       130   816.000000
68         20    106       136   110.400000
69        300    108       143  1500.200000
70        150     97       129  1115.000000
71         60    109       153   387.600000
72         90    100       127   700.000000
73        150     97       127   953.200000
74         45    114       146   304.000000
75         90     98       125   563.200000
76         45    105       134   251.000000
77         45    110       141   300.000000
78        120    100       130   500.400000
79        270    100       131  1729.000000
80         30    159       182   319.200000
81         45    149       169   344.000000
82         30    103       139   151.100000
83        120    100       130   500.000000
84         45    100       120   225.300000
85         30    151       170   300.000000
86         45    102       136   234.000000
87        120    100       157  1000.100000
88         45    129       103   242.000000
89         20     83       107    50.300000
90        180    101       127   600.100000
91         45    107       137   375.790244
92         30     90       107   105.300000
93         15     80       100    50.500000
94         20    150       171   127.400000
95         20    151       168   229.400000
96         30     95       128   128.200000
97         25    152       168   244.200000
98         30    109       131   188.200000
99         90     93       124   604.100000
100        20     95       112    77.700000
101        90     90       110   500.000000
102        90     90       100   500.000000
103        90     90       100   500.400000
104        30     92       108    92.700000
105        30     93       128   124.000000
106       180     90       120   800.300000
107        30     90       120    86.200000
108        90     90       120   500.300000
109       210    137       184  1860.400000
110        60    102       124   325.200000
111        45    107       124   275.000000
112        15    124       139   124.200000
113        45    100       120   225.300000
114        60    108       131   367.600000
115        60    108       151   351.700000
116        60    116       141   443.000000
117        60     97       122   277.400000
118        60    105       125   375.790244
119        60    103       124   332.700000
120        30    112       137   193.900000
121        45    100       120   100.700000
122        60    119       169   336.700000
123        60    107       127   344.900000
124        60    111       151   368.500000
125        60     98       122   271.000000
126        60     97       124   275.300000
127        60    109       127   382.000000
128        90     99       125   466.400000
129        60    114       151   384.000000
130        60    104       134   342.500000
131        60    107       138   357.500000
132        60    103       133   335.000000
133        60    106       132   327.500000
134        60    103       136   339.000000
135        20    136       156   189.000000
136        45    117       143   317.700000
137        45    115       137   318.000000
138        45    113       138   308.000000
139        20    141       162   222.400000
140        60    108       135   390.000000
141        60     97       127   375.790244
142        45    100       120   250.400000
143        45    122       149   335.400000
144        60    136       170   470.200000
145        45    106       126   270.800000
146        60    107       136   400.000000
147        60    112       146   361.900000
148        30    103       127   185.000000
149        60    110       150   409.400000
150        60    106       134   343.000000
151        60    109       129   353.200000
152        60    109       138   374.000000
153        30    150       167   275.800000
154        60    105       128   328.000000
155        60    111       151   368.500000
156        60     97       131   270.400000
157        60    100       120   270.400000
158        60    114       150   382.800000
159        30     80       120   240.900000
160        30     85       120   250.400000
161        45     90       130   260.400000
162        45     95       130   270.000000
163        45    100       140   280.900000
164        60    105       140   290.800000
165        60    110       145   300.000000
166        60    115       145   310.200000
167        75    120       150   320.400000
168        75    125       150   330.400000